### ISSUE TITLE
Unable to revive connection while creating pelias schema index on ES

### ISSUE THREAD

**Issue by pravink** [pelias/kubernetes#101]
When I ran a Schema create pod it throws below error:
**http://pelias-staging-es-elb-XXXX.ap-southeast-2.elb.amazonaws.com:9200/_nodes => getaddrinfo EAI_AGAINpelias-staging-es-elb-XXXXX.ap-southeast-2.elb.amazonaws.com pelias-staging-es-elb-XXXXX.ap-southeast-2.elb.amazonaws.com:9200
      at Log.error (/code/pelias/schema/node_modules/elasticsearch/src/lib/log.js:239:56)
      at checkRespForFailure (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:298:18)
      at HttpConnector.<anonymous> (/code/pelias/schema/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
      at ClientRequest.wrapper (/code/pelias/schema/node_modules/lodash/lodash.js:4929:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

Elasticsearch WARNING: 2019-09-06T01:30:05Z
  Unable to revive connection: http://pelias-staging-es-elb-XXXXX.ap-southeast-2.elb.amazonaws.com:9200/

Elasticsearch WARNING: 2019-09-06T01:30:05Z
  No living connections

{ Error: No Living connections
    at sendReqWithConnection (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:266:15)
    at next (/code/pelias/schema/node_modules/elasticsearch/src/lib/connection_pool.js:243:7)
    at process._tickCallback (internal/process/next_tick.js:61:11) message: 'No Living connections' }
please install mandatory plugins before continuing.**

here are the ES settings specified in values and passed it through configmap.tpl
elasticsearch:
  host: "pelias-staging-es-elb-XXXXX.ap-southeast-2.elb.amazonaws.com"
  port: 9200
  protocol: "http"
  keepAlive: false
  DeadTimeout: 1200
  maxRetries: 15

Do you have any idea how do i get workaround for this issue?

**Comment by orangejulius** [comment]
Hi @pravink,
This looks like an issue on your end with configuring Elasticsearch or your network, and not a bug report for this project.

If you need professional help setting up Pelias, we offer support plans at geocode.earth, you can email us at hello@geocode.earth if that might be helpful to you.
